title: "Blog about Software Development"
email: sashashpota@gmail.com
author:
  name: Sasha Shpota
  twitter: sashashpota
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sashashpota.com"
copyright: "© Oleksandr Shpota, 2017—2019"
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README.md
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - Rakefile

minima:
  date_format: "%-d %b %Y"
